name: flashbyte
description: "A new Flutter project."
publish_to: "none"
version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  basic_utils: ^5.8.2
  connectivity_plus: ^7.2.0
  crypto: ^3.0.7
  desktop_drop: ^0.7.1
  disable_battery_optimization: ^1.1.2
  dynamic_color: ^1.8.1
  external_path: ^2.2.0
  fast_file_picker: ^0.4.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  awesome_notifications: ^0.12.1
  heroine: ^0.5.0+2
  loading_indicator_m3e: ^0.1.1
  material_new_shapes: ^1.0.0
  mime: ^2.0.0
  motor: ^1.0.1
  open_file: ^4.0.0
  path_provider: ^2.1.5
  process_run: ^1.2.4
  saf: ^2.1.0
  shared_preferences: ^2.3.0
  uuid: ^4.5.1
  widget_zoom: ^0.0.4
  windowed_file_reader: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
